spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stomp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: stomp
    password: stomp